### ISSUE TITLE
CSW night glitches

### ISSUE THREAD

**Issue by charlienegri** [metno/discovery-metadata-catalog-ingestor#119]
![Screenshot from 2022-12-22 07-05-40.png](https://images.zenhubusercontent.com/62a32a63504b3c09aea160ba/3e746bfa-0138-4ba3-8bcb-a159975dcee7)
the ghc keeps failing briefly during the night, repeatedly, since last weekend  
the incidents auto-resolve but they repeat for a while one after the other, and at night only apparently

**Comment by charlienegri** [comment]
last night it was the development endpoint https://csw-dev.s-enda.k8s.met.no/ (see also chart here https://ghc.wps.met.no/resource/2?lang=en) but in the past days we had the same for the staging one too (see https://ghc.wps.met.no/resource/1?lang=en)

**Comment by charlienegri** [comment]
the error message from the ghc is always 
```
ExceptionReport> in response text
```
see for example 
![Screenshot from 2022-12-22 07-27-47.png](https://images.zenhubusercontent.com/62a32a63504b3c09aea160ba/82c69ffc-fb1a-4cb6-8e30-655236e8c0b1)

**Comment by charlienegri** [comment]
from `kubectl -n s-enda-dev describe pod pycsw-554ffbcbf6-zfxnq` I see  
```
Warning  PolicyViolation  5m29s                 kyverno-scan  policy require-requests-limits/validate-resources fail: validation error: CPU and memory resource requests and limits are required. rule validate-resources failed at path /spec/containers/0/resources/limits/
  Warning  PolicyViolation  4m28s                 kyverno-scan  policy require-ro-rootfs/validate-readOnlyRootFilesystem fail: validation error: Root filesystem must be read-only. rule validate-readOnlyRootFilesystem failed at path /spec/containers/0/securityContext/readOnlyRootFilesystem/
  Warning  PolicyViolation  3m38s                 kyverno-scan  policy drop-all-capabilities/require-drop-all error: failed to evaluate preconditions: failed to substitute variables in preconditions: failed to resolve request.operation at path /all/0/key: JMESPath query failed: Unknown key "operation" in path
  Warning  BackOff          96s (x2770 over 10h)  kubelet       Back-off restarting failed container
```

**Comment by charlienegri** [comment]
and  `kubectl -n s-enda-dev logs pycsw-554ffbcbf6-zfxnq` gives  
```
Defaulted container "pycsw" out of: pycsw, envsubst (init)
DEBUG:__main__:Setting up pycsw's data repository...
DEBUG:__main__:Repository URL: postgresql://csw_db_owner_user:GtcwFdQuKCXA6KmZTbdWP61Wb7KWNtl0tBmZhLGEUPM4aU1IqkNVk3WWDw8vYpuJ@postgis-operator:5432/csw_db
DEBUG:__main__:Waiting for 'postgresql://csw_db_owner_user:GtcwFdQuKCXA6KmZTbdWP61Wb7KWNtl0tBmZhLGEUPM4aU1IqkNVk3WWDw8vYpuJ@postgis-operator:5432/csw_db'...
DEBUG:__main__:Database is already up!
INFO:pycsw.core.admin:Creating database postgresql://csw_db_owner_user:GtcwFdQuKCXA6KmZTbdWP61Wb7KWNtl0tBmZhLGEUPM4aU1IqkNVk3WWDw8vYpuJ@postgis-operator:5432/csw_db
INFO:pycsw.core.admin:PostGIS 3.1.4 detected: Skipping SFSQL tables creation
INFO:pycsw.core.admin:Creating table records
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ReadOnlySqlTransaction: cannot execute CREATE TABLE in a read-only transaction


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/entrypoint.py", line 178, in <module>
    launch_pycsw(config, workers=args.workers, reload=args.reload)
  File "/usr/local/bin/entrypoint.py", line 86, in launch_pycsw
    db_handler(
  File "/usr/local/bin/entrypoint.py", line 129, in handle_postgresql_db
    admin.setup_db(database=database_url, table=table_name,
  File "/home/pycsw/pycsw/pycsw/core/admin.py", line 214, in setup_db
    records.create()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 928, in create
    bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table
    self.connection.execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.ReadOnlySqlTransaction) cannot execute CREATE TABLE in a read-only transaction

[SQL: 
CREATE TABLE records (
	identifier TEXT NOT NULL, 
	typename TEXT NOT NULL, 
	schema TEXT NOT NULL, 
	mdsource TEXT NOT NULL, 
	insert_date TEXT NOT NULL, 
	xml VARCHAR NOT NULL, 
	anytext TEXT NOT NULL, 
	language TEXT, 
	type TEXT, 
	title TEXT, 
	title_alternate TEXT, 
	abstract TEXT, 
	keywords TEXT, 
	keywordstype TEXT, 
	parentidentifier TEXT, 
	relation TEXT, 
	time_begin TEXT, 
	time_end TEXT, 
	topicategory TEXT, 
	resourcelanguage TEXT, 
	creator TEXT, 
	publisher TEXT, 
	contributor TEXT, 
	organization TEXT, 
	securityconstraints TEXT, 
	accessconstraints TEXT, 
	otherconstraints TEXT, 
	date TEXT, 
	date_revision TEXT, 
	date_creation TEXT, 
	date_publication TEXT, 
	date_modified TEXT, 
	format TEXT, 
	source TEXT, 
	crs TEXT, 
	geodescode TEXT, 
	denominator TEXT, 
	distancevalue TEXT, 
	distanceuom TEXT, 
	wkt_geometry TEXT, 
	servicetype TEXT, 
	servicetypeversion TEXT, 
	operation TEXT, 
	couplingtype TEXT, 
	operateson TEXT, 
	operatesonidentifier TEXT, 
	operatesoname TEXT, 
	degree TEXT, 
	classification TEXT, 
	conditionapplyingtoaccessanduse TEXT, 
	lineage TEXT, 
	responsiblepartyrole TEXT, 
	specificationtitle TEXT, 
	specificationdate TEXT, 
	specificationdatetype TEXT, 
	platform TEXT, 
	instrument TEXT, 
	sensortype TEXT, 
	cloudcover TEXT, 
	bands TEXT, 
	links TEXT, 
	PRIMARY KEY (identifier)
)

]
(Background on this error at: http://sqlalche.me/e/13/2j85)
```

**Comment by charlienegri** [comment]
more errors in the postgis-operator pod logs see https://chat.google.com/room/AAAAQFDXobQ/kWLJRVrqph4
I bet we are out of space on disk and this is causing the endpoints failures

**Comment by charlienegri** [comment]
should be solved now, see https://chat.google.com/room/AAAAQFDXobQ/kWLJRVrqph4
