### ISSUE TITLE
Failing delete

### ISSUE THREAD

**Issue by mortenwh** [metno/discovery-metadata-catalog-ingestor#87]
```
$> curl --data-binary "@precipitation_amount_st_92350.xml" localhost:5000/v1/insert
$> curl --data-binary "@precipitation_amount_st_92350.xml" localhost:5000/v1/delete/ee6fb8de-8ebd-4df6-95dd-83a44d21dfc7
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

Output from the server:
```
ERROR    Exception on /v1/delete/ee6fb8de-8ebd-4df6-95dd-83a44d21dfc7 [POST]
Traceback (most recent call last):
  File "/home/morten/miniconda3/envs/dmci/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/morten/miniconda3/envs/dmci/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/morten/miniconda3/envs/dmci/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/morten/miniconda3/envs/dmci/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/morten/miniconda3/envs/dmci/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/morten/miniconda3/envs/dmci/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/morten/metno_repos/discovery-metadata-catalog-ingestor/dmci/api/app.py", line 73, in post_delete
    err = self._distributor_wrapper(worker)
  File "/home/morten/metno_repos/discovery-metadata-catalog-ingestor/dmci/api/app.py", line 164, in _distributor_wrapper
    status, valid, _, failed, skipped, failed_msg = worker.distribute()
  File "/home/morten/metno_repos/discovery-metadata-catalog-ingestor/dmci/api/worker.py", line 123, in distribute
    obj = self.CALL_MAP[dist](
TypeError: dmci.distributors.file_dist.FileDist() got multiple values for keyword argument 'metadata_id'
127.0.0.1 - - [04/May/2022 14:24:11] "POST /v1/delete/ee6fb8de-8ebd-4df6-95dd-83a44d21dfc7 HTTP/1.1" 500 -
```

**Comment by johtoblan** [comment]
Problem is Worker.init has metadata_id as keyword argument, and kwargs is unpacked further down to FileDist, which has metadata_id as positional argument.
