### ISSUE TITLE
Improperly implemented use of pycsw update transaction and improved logging needed

### ISSUE THREAD

**Issue by mortenwh** [metno/discovery-metadata-catalog-ingestor#96]
Fix:

- [x] pycsw update function 
- [ ] add logging.debug to all pycsw functions

Update error message:
```
│ [2022-05-09 14:34:50,785]                 dmci.api.app:1455 ERROR    Exception on /v1/update [POST]                                                  │
│ Traceback (most recent call last):                                                                                                                   │
│   File "/usr/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app                                                                       │
│     response = self.full_dispatch_request()                                                                                                          │
│   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request                                                          │
│     rv = self.handle_user_exception(e)                                                                                                               │
│   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request                                                          │
│     rv = self.dispatch_request()                                                                                                                     │
│   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request                                                               │
│     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)                                                                     │
│   File "/usr/lib/python3.8/site-packages/dmci/api/app.py", line 67, in post_update                                                                   │
│     msg, code = self._insert_update_method_post("update", request)                                                                                   │
│   File "/usr/lib/python3.8/site-packages/dmci/api/app.py", line 126, in _insert_update_method_post                                                   │
│     err = self._distributor_wrapper(worker)                                                                                                          │
│   File "/usr/lib/python3.8/site-packages/dmci/api/app.py", line 165, in _distributor_wrapper                                                         │
│     status, valid, _, failed, skipped, failed_msg = worker.distribute()                                                                              │
│   File "/usr/lib/python3.8/site-packages/dmci/api/worker.py", line 130, in distribute                                                                │
│     obj_status, obj_msg = obj.run()                                                                                                                  │
│   File "/usr/lib/python3.8/site-packages/dmci/distributors/pycsw_dist.py", line 56, in run                                                           │
│     status, msg = self._update()                                                                                                                     │
│   File "/usr/lib/python3.8/site-packages/dmci/distributors/pycsw_dist.py", line 130, in _update                                                      │
│     ) % (self._translate(), self._worker._file_metadata_id.encode())                                                                                 │
│ AttributeError: 'UUID' object has no attribute 'encode'   
```

**Comment by mortenwh** [comment]
I have checked a bit further regarding the combination `<naming_authority>:<uuid>`. We can make that required, and update the current registrations. This will be better in the long run. So the dataset search should use `PropertyIsEqualTo`, and not `PropertyIsIn`.
